//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpsonPOSReport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int _plColumn_itemNumber {
            get {
                return ((int)(this["_plColumn_itemNumber"]));
            }
            set {
                this["_plColumn_itemNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int _plColumn_unitCost {
            get {
                return ((int)(this["_plColumn_unitCost"]));
            }
            set {
                this["_plColumn_unitCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int _plColumn_selectFFP {
            get {
                return ((int)(this["_plColumn_selectFFP"]));
            }
            set {
                this["_plColumn_selectFFP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int _plColumn_selectRebate {
            get {
                return ((int)(this["_plColumn_selectRebate"]));
            }
            set {
                this["_plColumn_selectRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int _plColumn_plusFFP {
            get {
                return ((int)(this["_plColumn_plusFFP"]));
            }
            set {
                this["_plColumn_plusFFP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int _plColumn_plusRebate {
            get {
                return ((int)(this["_plColumn_plusRebate"]));
            }
            set {
                this["_plColumn_plusRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int _plColumn_premierFFP {
            get {
                return ((int)(this["_plColumn_premierFFP"]));
            }
            set {
                this["_plColumn_premierFFP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int _plColumn_premierRebate {
            get {
                return ((int)(this["_plColumn_premierRebate"]));
            }
            set {
                this["_plColumn_premierRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public int _plColumn_mSelectFFP {
            get {
                return ((int)(this["_plColumn_mSelectFFP"]));
            }
            set {
                this["_plColumn_mSelectFFP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int _plColumn_mSelectRebate {
            get {
                return ((int)(this["_plColumn_mSelectRebate"]));
            }
            set {
                this["_plColumn_mSelectRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=METRO-GP1;Integrated Security=SSPI;Initial Catalog=METRO")]
        public string _DatabaseConnectionString {
            get {
                return ((string)(this["_DatabaseConnectionString"]));
            }
            set {
                this["_DatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _filePath_spaList {
            get {
                return ((string)(this["_filePath_spaList"]));
            }
            set {
                this["_filePath_spaList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _filePath_partnerList {
            get {
                return ((string)(this["_filePath_partnerList"]));
            }
            set {
                this["_filePath_partnerList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _filePath_priceList {
            get {
                return ((string)(this["_filePath_priceList"]));
            }
            set {
                this["_filePath_priceList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_btAddress {
            get {
                return ((bool)(this["_showColumn_btAddress"]));
            }
            set {
                this["_showColumn_btAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_btCity {
            get {
                return ((bool)(this["_showColumn_btCity"]));
            }
            set {
                this["_showColumn_btCity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_btState {
            get {
                return ((bool)(this["_showColumn_btState"]));
            }
            set {
                this["_showColumn_btState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_btZip {
            get {
                return ((bool)(this["_showColumn_btZip"]));
            }
            set {
                this["_showColumn_btZip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_stCustomer {
            get {
                return ((bool)(this["_showColumn_stCustomer"]));
            }
            set {
                this["_showColumn_stCustomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_stAddress {
            get {
                return ((bool)(this["_showColumn_stAddress"]));
            }
            set {
                this["_showColumn_stAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_stCity {
            get {
                return ((bool)(this["_showColumn_stCity"]));
            }
            set {
                this["_showColumn_stCity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_stState {
            get {
                return ((bool)(this["_showColumn_stState"]));
            }
            set {
                this["_showColumn_stState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _showColumn_stZip {
            get {
                return ((bool)(this["_showColumn_stZip"]));
            }
            set {
                this["_showColumn_stZip"] = value;
            }
        }
    }
}
